[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=elevende
autologin-user=user
autologin-user-timeout=0
autologin-session=elevende
autologin-in-background=false
greeter-hide-users=false

[Seat:0]
user-session=elevende
autologin-user=user
autologin-user-timeout=0
autologin-session=elevende
autologin-in-background=false
